function spike = remove_spikes(trial,sect_data,boxX,boxY,xsize,ysize,spike,start,finish)
%function spike = remove_spikes(trial,sect_data,boxX,boxY,xsize,ysize,spike,start,finish)
%
%removes spike from spike structure 


Y1 = sect_data(1,:) + boxY(1);
Y2 = sect_data(1,:) + boxY(2);
Y3 = sect_data(1,:) + boxY(3);
Y4 = sect_data(1,:) + boxY(4);
X1 = sect_data(2,:) + boxX(1);
X2 = sect_data(2,:) + boxX(2);
X3 = sect_data(2,:) + boxX(3);
X4 = sect_data(2,:) + boxX(4);

index = 	(Y1<1) + ...
   		(Y2<1) + ...
   		(Y3<1) + ...
   		(Y4<1) + ...
   		(X1<1) + ...
   		(X2<1) + ...
   		(X3<1) + ...
   		(X4<1) + ...
   		(Y1>ysize) + ...
   		(Y2>ysize) + ...
   		(Y3>ysize) + ...
   		(Y4>ysize) + ...
   		(X1>xsize) + ...
   		(X2>xsize) + ...
   		(X3>xsize) + ...
   		(X4>xsize);


if sum(index)~=0
   %then ignore all spikes during this section
   for c = 1:size(spike.trial(trial).cluster,2)	%loop over clusters
      spike_index = find((spike.trial(trial).cluster(c).spikes > start)  &  (spike.trial(trial).cluster(c).spikes < finish));
      spike.trial(trial).cluster(c).spikes(spike_index) = [];
      spike.trial(trial).cluster(c).spikecount = spike.trial(trial).cluster(c).spikecount - length(spike_index);
   end
end